apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resourcequota.yaml
  - secret.yaml
  - configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - hazelcast-jmx-exporter-configmap.yaml
  - hazelcast-deployment.yaml
  - hazelcast-service.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - ingress.yaml
  - issue-service-deployment.yaml
  - issue-service-hpa.yaml
  - issue-service-service.yaml
  - issue-service-ingress.yaml

images:
  - name: message-service
    newName: docker.io/miqui/message-service
    newTag: latest
  - name: issue-service
    newName: docker.io/miqui/issue-service
    newTag: latest
